all:
	gcc --include src/main.c src/snake_cube.c -o bin/snake_cube -Wall
test:
	gcc --include src/snake_cube.c src/snake_cube_spec.c -o bin/snake_cube_spec -Wall
clean:
	rm bin/snake_cube bin/snake_cube_spec
